### ISSUE TITLE
Binary Request: [1.13.1.18-snapshot]

### ISSUE THREAD

**Issue by ceco987** [DEAKSoftware/Synergy-Binaries#1]
Hello, would you kindly provide built version 1.13.1.18-snapshot (or any of the pre-releases after 1.13.1.5)? The reasoning is that they fixed an encoding issue which currently prevents me to type to multiple languages in windows and I struggle to compile the version myself, despite the provided instructions.
Thank you for your attention.

**Comment by DominikDeak** [comment]
https://github.com/DEAKSoftware/Synergy-Binaries/releases/tag/1.13.1.18-snapshot

See if that works for you.

By the way, the build script now accepts tags and commit hashes in case you want to build a specific version. For example:

```powershell
python.exe Scripts\build.py --checkout 1.13.1.18-snapshot
```

**Comment by ceco987** [comment]
Thank you for the provided info and build :)
