### ISSUE TITLE
Please Answer..Important!

### ISSUE THREAD

**Issue by foco76** [DEAKSoftware/Synergy-Binaries#15]
what is the difference between synergy 1 , synergy 2 and synergy 3?
Thank you!

**Comment by DominikDeak** [comment]
I'm not the official maintainer of the Synergy project. This question is better asked on the Synergy repository:
https://github.com/symless/synergy-core/issues

I'm guessing Synergy 2 is like a rewrite of the original Synergy app, but I am not sure as i never used it.

**Comment by foco76** [comment]
Thank You!
