### ISSUE TITLE
Build Fails with Colorama Issue

### ISSUE THREAD

**Issue by amdavidson** [DEAKSoftware/Synergy-Binaries#20]
On Debian Bullseye running `./Scripts/Install.py` then `./Scripts/Build.py` fails with an error: ```AttributeError: Module 'colorama' has no attribute 'init'```

Running `sudo python3 -m pip install colorama` shows that the dependency is installed.

### System Information

* Operating System: Debian Bullseye
* Build Environment: ./Scripts/Install.py
* Synergy Version: Synergy 1.14.5.17-stable

### Steps to Reproduce

1. Start with a clean Debian Bullseye
2. Run ./Scripts/Install.py
3. Run ./Scripts/build.py

### Expected Results

Build current commit of Synergy

### Actual Results

Fails with error: ```AttributeError: module `colorama` has no attribute 'init'```

**Comment by DominikDeak** [comment]
What happens when you run `./Scripts/Install.py --upgrade` ?

**Comment by amdavidson** [comment]
I created a new, clean debian VM and was unable to reproduce. I suspect it was an issue with my original system.

I am getting new unrelated errors and have not had time to diagnose. Closing for now.
