### ISSUE TITLE
Binary Request: V1.14.6

### ISSUE THREAD

**Issue by qin9125** [DEAKSoftware/Synergy-Binaries#21]
Thank you.

**Comment by DominikDeak** [comment]
I'm assuming this the version you're after?

https://github.com/symless/synergy-core/releases/tag/1.14.6.0-snapshot

**Comment by DominikDeak** [comment]
Lest binaries for 1.14.6.xx is now available here.
https://github.com/DEAKSoftware/Synergy-Binaries/releases/tag/1.14.6.13-snapshot
