### ISSUE TITLE
Binary Request: Working version for macOS Ventura 13.2

### ISSUE THREAD

**Issue by JavaScriptBach** [DEAKSoftware/Synergy-Binaries#22]
Is there a working version for macOS Ventura 13.2? Neither the 1.14.6.13-snapshot nor 1.14.5.17-stable releases work for me.
- macOS thinks the 1.14.6.13-snapshot is broken and won't even run the code.
- Running 1.14.5.17-stable pops up a dialog saying that access must be granted to accessibility features in System Settings, but this persists even after I grant the app access.

**Comment by JavaScriptBach** [comment]
Nevermind, I fixed this by using the workaround in #2 and also running
```
sudo tccutil reset Accessibility
```

**Comment by DominikDeak** [comment]
You can also fix this issue by going into Settings -> Privacy & Security -> Accessibility and turn on these items:

![Screenshot 2023-01-30 at 4 06 16 pm](https://user-images.githubusercontent.com/1121604/215392035-33f26249-4120-4cf1-9577-9ad7be620451.png)
