### ISSUE TITLE
Binary Request: Windows 32 bits

### ISSUE THREAD

**Issue by mgtroyas** [DEAKSoftware/Synergy-Binaries#27]
I've built a Windows XP retro gaming PC and Synergy works great for sharing input between it, my main PC and my laptop on the same desk. But I must use the last 32 bit build for 32 bits XP. Would be great to have a 32 bit build for users within an old 32 bit Windows OS like me.

**Comment by DominikDeak** [comment]
Unfortunately the build scripts are not capable of targeting build environments other than the host machine the project is being built on. As I don't have access to a machine with 32-bit Windows installed, publishing 32-bit releases is unlikely at this stage. I'm sorry.

**Comment by FLZeng** [comment]
I've compiled the x86 version. You may want to give it a try.
https://github.com/FLZeng/synergy-core/releases

**Comment by mgtroyas** [comment]
Well, the x86 binary doesn't work on Windows XP, when starting the service it gives an error and executing the binary manually gives a "This is not a Win32 application" error, which is probably due to being compiled against a too high VisualC++ Redistributable, which is not supported under Windows XP (latest one compatible is 2019, probably compiling against it would fix it).

BUT... the portable binaries provided were extremely useful: I installed the old 1.8.8 stable version on the Windows XP machine, acting as server, the x64 installer version on my personal Windows 11 PC, and the portable version on my corporate Windows 10 laptop, where I don't have admin rights, disabled TLS encryption on both modern PCs... and they connected as clients to the server without problem! Thank you very much!!
