### ISSUE TITLE
Binary Request: 3.x.x

### ISSUE THREAD

**Issue by Rozzemak** [DEAKSoftware/Synergy-Binaries#28]
Synergy released 3.x.x version of their software. I cannot find it in their public repo tho. I guess that only 1.x.x will be open source ? 
https://symless.com/synergy-blog/official-launch-of-synergy-3
(3.x.x version moniker may not correspond with actual synergy 3 binary versioning.. 😄 )

**Comment by DominikDeak** [comment]
> I guess that only 1.x.x will be open source ?

I can't find a specific repository for v3 of the software. It might be closed source?

**Comment by Rozzemak** [comment]
Yea. Same situation as with failed synergy 2 fork.

Synergy 3 is closed source.
Closing this issue.

**Comment by DominikDeak** [comment]
> Same situation as with failed synergy 2 fork.

Which is kinda interesting, because if they indeed forked it from the v1 source tree, then they'd be obligated to make it open source, as per GPL.

**Comment by Rozzemak** [comment]
W8 what? Synergy is published under GPL ? I thought it was MIT.
Most interesting.

Also, no, I don't think synergy 2 is a fork of sym-core. I really don't know why i wrote the "fork" got there.. small brain malfunction, sorry.
