### ISSUE TITLE
How to get the synergy version for the Sonoma Mac?

### ISSUE THREAD

**Issue by talent-jsdev** [DEAKSoftware/Synergy-Binaries#30]
I want to know how to get the synergy version for the Sonoma Mac.

**Comment by DominikDeak** [comment]
Currently there is no binaries built specifically on the Sonoma OS, but the latest build should work on Sonoma:

https://github.com/DEAKSoftware/Synergy-Binaries/releases/tag/1.14.7.5-snapshot
