### ISSUE TITLE
error in connecting

### ISSUE THREAD

**Issue by Ghostretri** [DEAKSoftware/Synergy-Binaries#31]
hello. i have seen an issue where it connects and works perfectly if i use my laptop with ubuntu OS as the server, but when i use my windows laptop as the server it onnects, but the cursor doesnt move over to the ubuntu screen. please advice

**Comment by DominikDeak** [comment]
Issues related to operating Synergy should be posted on the official github page here:
https://github.com/symless/synergy-core/issues
