### ISSUE TITLE
Binary Request: 1.15.0

### ISSUE THREAD

**Issue by Unknown-Guy** [DEAKSoftware/Synergy-Binaries#32]
Synergy [1.15.0](https://github.com/symless/synergy/releases/tag/1.15.0%2Br3) was releases last week

**Comment by poo0054** [comment]
+1

**Comment by DominikDeak** [comment]
Sorry everyone for neglecting things a bit, I've been quite busy lately and I don't have my my machines for building releases at hand. 

As @Unknown-Guy said, looks like Synergy's new open source commitment will also mean providing binaries directly on their repository, which I think is quite excellent, and good on them.  Check out the binaries here: https://github.com/deskflow/deskflow/releases

These new developments might also mean the `Synergy-Binaries` project is probably now redundant?
