### ISSUE TITLE
Problem with compiling - Error with google test sumodules

### ISSUE THREAD

**Issue by pabloh84** [DEAKSoftware/Synergy-Binaries#9]
(maybe is a rookie mistake, sorry to bother you) I run in this error when trying to run build.py script 

### System Information

* Operating System: _[Ubuntu 20.04]_  
* Build Environment: _[System default following documentation]_  
* Synergy Version: _[master (no versión specified]_  

### Steps to Reproduce

1. Download repo as instructed in [Getting Started](https://github.com/DEAKSoftware/Synergy-Binaries/blob/1.14.4.37-stable/Documentation/GettingStarted.md)
2. Followed [prerequisites](https://github.com/DEAKSoftware/Synergy-Binaries/blob/1.14.4.37-stable/Documentation/BuildingOnLinux.md#prerequisites)
3. Run ./Scripts/build.py

### Expected Results

Compilation should proceed as smoothly

### Actual Results

Error with google test module 

<pre><font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries</b></font>$ ./Scripts/build.py 
<font color="#AD7FA8">Loading configuration...</font>
<b>configPath: </b>/home/pablo/Synergy-Binaries/Scripts/config.txt
<font color="#AD7FA8">Git configuration...</font>
<font color="#34E2E2">git config --get remote.origin.url</font>
<font color="#34E2E2">git rev-parse --show-toplevel</font>
<b>toplevelPath: </b>/home/pablo/Synergy-Binaries
<b>upstreamURL: </b>https://github.com/DEAKSoftware/Synergy-Binaries.git
<b>queriedURL: </b>https://github.com/DEAKSoftware/Synergy-Binaries.git
<font color="#AD7FA8">Path configuration...</font>
<b>productRepoPath: </b>/home/pablo/Synergy-Binaries/Synergy-Core
<b>productBuildPath: </b>/home/pablo/Synergy-Binaries/Synergy-Core/build
<b>binariesPath: </b>/home/pablo/Synergy-Binaries/Binaries
<b>toolsPath: </b>/home/pablo/Synergy-Binaries/Tools
<font color="#AD7FA8">Version configuration...</font>
<b>platformVersion: </b>ubuntu-20.04-focal-x86_64
<font color="#34E2E2">git describe --tags --abbrev=0</font>
<b>lastTag: </b>1.14.4.37-stable
<font color="#34E2E2">git rev-parse --short=8 HEAD</font>
<b>productVersion: </b>1.14.4.37
<b>productStage: </b>stable
<b>productRevision: </b>41e070ea
<b>productPackageName: </b>synergy-1.14.4.37-stable-ubuntu-20.04-focal-x86_64
<font color="#AD7FA8">Updating Git submodules...</font>
<font color="#34E2E2">git submodule status</font>
-ad7273eb153ea05e307d401bdf8682fad132223f Synergy-Core
<font color="#34E2E2">git submodule update --init --remote --recursive</font>
Submodule &apos;Synergy-Core&apos; (https://github.com/symless/synergy-core.git) registered for path &apos;Synergy-Core&apos;
Cloning into &apos;/home/pablo/Synergy-Binaries/Synergy-Core&apos;...
Submodule path &apos;Synergy-Core&apos;: checked out &apos;bcfeb251a923d0fb6deb3aebf4e3e1652d30d393&apos;
Submodule &apos;ext/WinToast&apos; (https://github.com/mohabouje/WinToast) registered for path &apos;Synergy-Core/ext/WinToast&apos;
Submodule &apos;ext/googletest&apos; (https://github.com/google/googletest.git) registered for path &apos;Synergy-Core/ext/googletest&apos;
Submodule &apos;ext/pugixml&apos; (https://github.com/zeux/pugixml) registered for path &apos;Synergy-Core/ext/pugixml&apos;
Cloning into &apos;/home/pablo/Synergy-Binaries/Synergy-Core/ext/WinToast&apos;...
Cloning into &apos;/home/pablo/Synergy-Binaries/Synergy-Core/ext/googletest&apos;...
Cloning into &apos;/home/pablo/Synergy-Binaries/Synergy-Core/ext/pugixml&apos;...
Submodule path &apos;Synergy-Core/ext/WinToast&apos;: checked out &apos;5e441fd03543b999edb663caf8df7be37c0d575c&apos;
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path &apos;ext/googletest&apos;
Failed to recurse into submodule path &apos;Synergy-Core&apos;
<font color="#EF2929">error: </font>Command exited with error.</pre>

**Comment by DominikDeak** [comment]
Try updating the `googletest` submodule manually. See if that makes a difference. 
```
pushd Synergy-Core
git submodule update --remote ext/googletest
popd
./Scripts/clean.py
./Scripts/build.py
```

**Comment by pabloh84** [comment]
Thanks for your help... I am not quite knowledgeable with GIT

Updating the module complains about missing single revision... 

<pre><font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries</b></font>$ pushd Synergy-Core
~/Synergy-Binaries/Synergy-Core ~/Synergy-Binaries
<font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries/Synergy-Core</b></font>$ git submodule update --remote ext/googletest
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path &apos;ext/googletest&apos;
<font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries/Synergy-Core</b></font>$ popd
</pre>

And the other option seems to run into some conflicts...

<pre><font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries</b></font>$ git submodule update --init --recursive
<font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries</b></font>$ git submodule foreach --recursive git fetch
Entering &apos;Synergy-Core&apos;
Entering &apos;Synergy-Core/ext/WinToast&apos;
Entering &apos;Synergy-Core/ext/googletest&apos;
Entering &apos;Synergy-Core/ext/pugixml&apos;
<font color="#4E9A06"><b>pablo@pablo-VirtualBox</b></font>:<font color="#3465A4"><b>~/Synergy-Binaries</b></font>$ git submodule foreach git merge origin master
Entering &apos;Synergy-Core&apos;
Auto-merging src/test/unittests/shared/SerialKeyEditionTests.cpp
Auto-merging src/lib/shared/SerialKeyEdition.cpp
Auto-merging src/gui/src/LicenseManager.cpp
CONFLICT (content): Merge conflict in src/gui/src/LicenseManager.cpp
Auto-merging cmake/Version.cmake
Auto-merging ChangeLog
CONFLICT (content): Merge conflict in ChangeLog
Automatic merge failed; fix conflicts and then commit the result.
fatal: run_command returned non-zero status for Synergy-Core
.
</pre>

**Comment by DominikDeak** [comment]
There is something not quite right with the sate of your local repository. I can't replicate the issue on my end. I suggest to remove the entire `Synergy-Binaries` folder and re-clone everything:

```
mv Synergy-Binaries Synergy-Binaries.backup
git clone --recurse-submodules https://github.com/DEAKSoftware/Synergy-Binaries.git
cd Synergy-Binaries
./Scripts/Install/InstallLinux.sh --upgrade   
./Scripts/build.py
```

**Comment by pabloh84** [comment]
Sorry to keep bothering but that's the thing... Clean clone with no changes do not work :-) 

Attaching logs of both command lists:

[CleanCloneLogs.txt](https://github.com/DEAKSoftware/Synergy-Binaries/files/9017032/CleanCloneLogs.txt)

[RemovingSubmoduleLogs.txt](https://github.com/DEAKSoftware/Synergy-Binaries/files/9017033/RemovingSubmoduleLogs.txt)

**Comment by DominikDeak** [comment]
> Sorry to keep bothering but that's the thing...

It's all good, man. I'm sorry this is issue causing you grief.

I had a look around on the internet, apparently some people experienced similar issues in older versions of git (see example [here](https://stackoverflow.com/questions/7605469/git-submodules-pulling-into-a-new-clone-of-the-super-project/8573310#8573310)). Looking at the logs, your linux distribution uses an older git version 2.25.1:

>git is already the newest version (1:2.25.1-1ubuntu3.4).

The git version I use is 2.36.1, which I suspect fixes some of the issues you're experiencing. If you are willing to experiment around, I suggest getting the latest git version directly from `git-core/ppa`. Here how you can do it (I lifted the details from [this page](https://www.linuxcapable.com/how-to-install-and-update-latest-git-on-ubuntu-20-04/)):

```
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt update
sudo apt upgrade -y
sudo apt install git -y
git --version
```

Then try again: 

```
mv Synergy-Binaries Synergy-Binaries.backup
git clone --recurse-submodules https://github.com/DEAKSoftware/Synergy-Binaries.git
cd Synergy-Binaries
./Scripts/build.py
```

**Comment by pabloh84** [comment]
Updated to latest GIT version and now it's working like charm... 

First time I've come across something like this! One would expect any GIT version to work regardless the repo, (maybe there could be some missing features, but not being able to update the sub-modules... Who could have guessed??)  

Anyway, thank you very much for your support and patience, and thank you for your work on this repository. It has been a lifesaver. Also thanks for releasing the Ubuntu 22.04 version (it kind makes my effort to compile it useless, but quite more convenient!)

**Comment by DominikDeak** [comment]
No worries. I recently updated my Linux to 22.04, so i'll be building Synergy against the most recent LTS from now on.
